name: budget_tracker
description: "A Budget Tracker."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # for internationalization
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  get_it: ^8.0.2
  uuid: ^4.5.1
  hive: ^2.2.3
  hive_generator: ^2.0.1
  hive_flutter: ^1.1.0
  bloc: ^8.1.4
  bloc_test: ^9.1.7
  test: ^1.25.7
  flutter_bloc: ^8.1.6
  provider: ^6.1.2
  # Annotations for better user experience
  meta: ^1.15.0  
  font_awesome_flutter: ^10.8.0
  equatable: ^2.0.7
  fl_chart: ^0.69.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.4

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - lib/config/localization/
