import 'package:budget_tracker/features/budget/data/models/budget_models/budget_breakdown_type.dart';
import 'package:budget_tracker/features/budget/data/models/budget_models/budget_category_type.dart';
import 'package:budget_tracker/features/budget/data/models/budget_models/budget_period_type.dart';
import 'package:budget_tracker/features/budget/data/models/transaction_models/category_to_wallet_transaction.dart';
import 'package:budget_tracker/features/budget/data/models/transaction_models/wallet_to_category_transaction.dart';
import 'package:budget_tracker/features/budget/data/models/transaction_models/wallet_to_wallet_with_category_transaction.dart';
import 'package:budget_tracker/features/wallet/wallet_models/debt_wallet.dart';
import 'package:budget_tracker/features/wallet/wallet_models/saving_wallet.dart';
import 'package:budget_tracker/features/wallet/wallet_models/spending_wallet.dart';
import 'package:budget_tracker/hive_helper/expense_type_adapter.dart';
import 'package:budget_tracker/hive_helper/icon_data_adapter.dart';
import 'package:budget_tracker/models/category_models/category.dart';
import 'package:budget_tracker/models/styled_text.dart';
import 'package:budget_tracker/models/styled_text_key.dart';
import 'package:budget_tracker/models/item_theme.dart';
import 'package:budget_tracker/models/category_models/head_category.dart';
import 'package:hive_flutter/adapters.dart';
import 'package:budget_tracker/features/budget/data/models/budget_models/budget_breakdown.dart';
import 'package:budget_tracker/features/budget/data/models/budget_models/budget_category.dart';
import 'package:budget_tracker/features/budget/data/models/budget_models/budget_head_categories.dart';
import 'package:budget_tracker/features/budget/data/models/budget_models/budget_period.dart';
import 'package:budget_tracker/features/budget/data/models/budget_models/budget.dart';

void registerAdapters() {
  Hive.registerAdapter(ItemThemeAdapter());
  Hive.registerAdapter(StyledTextKeyAdapter());
  Hive.registerAdapter(StyledTextAdapter());
  Hive.registerAdapter(HeadCategoryAdapter());
  Hive.registerAdapter(CategoryAdapter());
  Hive.registerAdapter(ColorAdapter());
  Hive.registerAdapter(IconDataAdapter());
  Hive.registerAdapter(ExpenseTypeAdapter());
  Hive.registerAdapter(BudgetBreakdownAdapter());
  Hive.registerAdapter(BudgetBreakdownTypeAdapter());
  Hive.registerAdapter(BudgetCategoryAdapter());
  Hive.registerAdapter(BudgetCategoryTypeAdapter());
  Hive.registerAdapter(BudgetHeadCategoryAdapter());
  Hive.registerAdapter(BudgetPeriodTypeAdapter());
  Hive.registerAdapter(BudgetPeriodAdapter());
  Hive.registerAdapter(BudgetAdapter());
  // Hive.registerAdapter(TransactionAdapter());
  Hive.registerAdapter(CategoryToWalletTransactionAdapter());
  Hive.registerAdapter(WalletToCategoryTransactionAdapter());
  Hive.registerAdapter(WalletToWalletWithCategoryTransactionAdapter());
  // Hive.registerAdapter(WalletAdapter());
  Hive.registerAdapter(SpendingWalletAdapter());
  Hive.registerAdapter(SavingWalletAdapter());
  Hive.registerAdapter(DebtWalletAdapter());
}
